// Firestore path builders — the single source of truth for where things live.
export const P = {
  gym: (g: string) => `gyms/${g}`,
  user: (u: string) => `users/${u}`,
  notifications: (u: string) => `users/${u}/notifications`,
  noticeReads: (u: string) => `users/${u}/noticeReads`,
  memberProfiles: (g: string) => `gyms/${g}/memberProfiles`,
  memberProfile: (g: string, u: string) => `gyms/${g}/memberProfiles/${u}`,
  username: (g: string, name: string) => `gyms/${g}/usernames/${name}`,
  classes: (g: string) => `gyms/${g}/classes`,
  trainers: (g: string) => `gyms/${g}/trainers`,
  classSlots: (g: string) => `gyms/${g}/classSlots`,
  classSlot: (g: string, classId: string, date: string) => `gyms/${g}/classSlots/${classId}_${date}`,
  classBookings: (g: string) => `gyms/${g}/classBookings`,
  classBooking: (g: string, slotId: string, u: string) => `gyms/${g}/classBookings/${slotId}_${u}`,
  trainerBookings: (g: string) => `gyms/${g}/trainerBookings`,
  presence: (g: string) => `gyms/${g}/userPresence`,
  presenceOf: (g: string, u: string) => `gyms/${g}/userPresence/${u}`,
  checkIns: (g: string) => `gyms/${g}/checkIns`,
  checkInStats: (g: string) => `gyms/${g}/checkInStats`,
  checkInStat: (g: string, day: string) => `gyms/${g}/checkInStats/${day}`,
  visit: (g: string, u: string, day: string) => `gyms/${g}/gymVisits/${u}_${day}`,
  gamification: (g: string, u: string) => `gyms/${g}/gamification/${u}`,
  records: (g: string, u: string) => `gyms/${g}/personalRecords/${u}/records`,
  badges: (g: string, u: string) => `gyms/${g}/userBadges/${u}/earned`,
  leaderboard: (g: string, month: string) => `gyms/${g}/leaderboard/${month}/entries`,
  leaderboardEntry: (g: string, month: string, u: string) => `gyms/${g}/leaderboard/${month}/entries/${u}`,
  notices: (g: string) => `gyms/${g}/notices`,
  workoutLogs: (g: string, u: string) => `gyms/${g}/workoutLogs/${u}/logs`,
  bodyMetrics: (g: string, u: string) => `gyms/${g}/bodyMetrics/${u}/entries`,
  plans: (g: string, u: string) => `gyms/${g}/workoutPlans/${u}/plans`,
  swipes: (g: string) => `gyms/${g}/buddySwipes`,
  swipe: (g: string, from: string, to: string) => `gyms/${g}/buddySwipes/${from}_${to}`,
  matches: (g: string) => `gyms/${g}/buddyMatches`,
  match: (g: string, id: string) => `gyms/${g}/buddyMatches/${id}`,
  messages: (g: string, id: string) => `gyms/${g}/buddyMatches/${id}/messages`,
};

export const matchIdFor = (a: string, b: string) => [a, b].sort().join("_");
